# Generated by Django 4.2.7 on 2025-11-12 10:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True)),
                ('email_provider', models.CharField(blank=True, default='Gmail', max_length=100)),
                ('sms_enabled', models.BooleanField(default=True)),
                ('sms_provider', models.CharField(blank=True, default='Twilio', max_length=100)),
                ('whatsapp_enabled', models.BooleanField(default=False)),
                ('whatsapp_provider', models.CharField(blank=True, default='Meta', max_length=100)),
                ('facebook_enabled', models.BooleanField(default=False)),
                ('facebook_provider', models.CharField(blank=True, default='Meta', max_length=100)),
                ('instagram_enabled', models.BooleanField(default=False)),
                ('instagram_provider', models.CharField(blank=True, default='Meta', max_length=100)),
                ('crm_provider', models.CharField(default='SimplyBook.me', max_length=100)),
                ('crm_connected', models.BooleanField(default=False)),
                ('crm_last_synced', models.DateTimeField(blank=True, null=True)),
                ('lead_followup_enabled', models.BooleanField(default=True)),
                ('booking_reminder_enabled', models.BooleanField(default=True)),
                ('confirmation_enabled', models.BooleanField(default=True)),
                ('post_session_enabled', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('in_app_notifications', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_settings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
