# Generated by Django 4.2.7 on 2025-11-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='crm_api_key',
            field=models.CharField(blank=True, help_text='Encrypted in production', max_length=255),
        ),
    ]
