# Generated by Django 4.2.7 on 2025-11-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='crm_client_id',
            field=models.CharField(blank=True, help_text='Client ID in CRM system (SimplyBook.me, etc.)', max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='crm_synced_at',
            field=models.DateTimeField(blank=True, help_text='Last time synced to CRM', null=True),
        ),
    ]
