# Generated by Django 4.2.7 on 2025-11-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_crm_client_id_lead_crm_synced_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='description_of_enquiry',
            field=models.TextField(blank=True, help_text='Description of the enquiry or request'),
        ),
        migrations.AddField(
            model_name='lead',
            name='potential_value',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Potential revenue value of this lead', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price quoted or expected', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='service_type',
            field=models.CharField(blank=True, choices=[('consultation', 'Consultation'), ('coaching', 'Coaching'), ('therapy', 'Therapy'), ('session', 'Session'), ('workshop', 'Workshop'), ('other', 'Other')], help_text='Type of service requested', max_length=50),
        ),
    ]
