# Generated by Django 4.2.7 on 2025-11-14 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OnboardingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.CharField(choices=[('welcome', 'Welcome'), ('crm_connection', 'CRM Connection'), ('booking_setup', 'Booking Setup'), ('channels_setup', 'Channels Setup'), ('automations_setup', 'Automations Setup'), ('complete', 'Complete')], default='welcome', max_length=50)),
                ('completed_steps', models.JSONField(blank=True, default=list)),
                ('crm_provider', models.CharField(blank=True, max_length=100)),
                ('crm_api_key', models.CharField(blank=True, max_length=255)),
                ('crm_company_login', models.CharField(blank=True, max_length=255)),
                ('booking_provider', models.CharField(blank=True, max_length=100)),
                ('booking_api_key', models.CharField(blank=True, max_length=255)),
                ('email_provider', models.CharField(blank=True, max_length=100)),
                ('email_smtp_host', models.CharField(blank=True, max_length=255)),
                ('email_smtp_user', models.CharField(blank=True, max_length=255)),
                ('email_smtp_password', models.CharField(blank=True, max_length=255)),
                ('sms_provider', models.CharField(blank=True, max_length=100)),
                ('sms_twilio_sid', models.CharField(blank=True, max_length=255)),
                ('sms_twilio_token', models.CharField(blank=True, max_length=255)),
                ('sms_twilio_phone', models.CharField(blank=True, max_length=50)),
                ('whatsapp_provider', models.CharField(blank=True, max_length=100)),
                ('whatsapp_twilio_sid', models.CharField(blank=True, max_length=255)),
                ('whatsapp_twilio_token', models.CharField(blank=True, max_length=255)),
                ('facebook_page_id', models.CharField(blank=True, max_length=255)),
                ('facebook_access_token', models.CharField(blank=True, max_length=500)),
                ('instagram_account_id', models.CharField(blank=True, max_length=255)),
                ('instagram_access_token', models.CharField(blank=True, max_length=500)),
                ('setup_notes', models.TextField(blank=True)),
                ('setup_completed_by', models.CharField(blank=True, max_length=255)),
                ('setup_completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='onboarding', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Onboarding Steps',
            },
        ),
    ]
