# Generated by Django 4.2.7 on 2025-11-13 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('upsell', 'Upsell'), ('cross_sell', 'Cross-sell'), ('renewal', 'Renewal'), ('expansion', 'Expansion'), ('win_back', 'Win-back')], max_length=50)),
                ('status', models.CharField(choices=[('identified', 'Identified'), ('in_progress', 'In Progress'), ('converted', 'Converted'), ('lost', 'Lost')], default='identified', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('estimated_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confidence_score', models.IntegerField(default=50)),
                ('reasoning', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='leads.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Opportunities',
                'ordering': ['-confidence_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_type', models.CharField(choices=[('conversion_rate', 'Conversion Rate'), ('response_rate', 'Response Rate'), ('engagement_rate', 'Engagement Rate'), ('average_response_time', 'Average Response Time'), ('lead_velocity', 'Lead Velocity'), ('revenue_per_lead', 'Revenue Per Lead'), ('upsell_rate', 'Upsell Rate')], max_length=50)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period_start', models.DateTimeField()),
                ('period_end', models.DateTimeField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period_end', '-created_at'],
                'indexes': [models.Index(fields=['user', 'metric_type', 'period_end'], name='business_in_user_id_65aab9_idx')],
            },
        ),
        migrations.CreateModel(
            name='BusinessInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('missed_opportunity', 'Missed Opportunity'), ('upsell_potential', 'Upsell Potential'), ('conversion_risk', 'Conversion Risk'), ('engagement_trend', 'Engagement Trend'), ('performance_metric', 'Performance Metric'), ('recommendation', 'Recommendation')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('metric_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('metric_label', models.CharField(blank=True, max_length=100)),
                ('action_items', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='insights', to='leads.lead')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['user', 'type', 'is_resolved'], name='business_in_user_id_113ebc_idx'), models.Index(fields=['created_at'], name='business_in_created_31d3e8_idx')],
            },
        ),
    ]
