# Generated by Django 4.2.7 on 2025-11-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='crm_client_id',
            field=models.CharField(blank=True, help_text='Client ID in CRM system', max_length=255),
        ),
    ]
