# Generated by Django 4.2.7 on 2025-11-17 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_crm_client_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='property',
            field=models.CharField(blank=True, help_text='Property name or address for the booking', max_length=255),
        ),
        migrations.AddField(
            model_name='booking',
            name='revenue',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Revenue generated from this booking', max_digits=10, null=True),
        ),
    ]
