# Generated by Django 4.2.7 on 2025-11-13 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automation',
            name='channel',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('whatsapp', 'WhatsApp'), ('facebook', 'Facebook'), ('instagram', 'Instagram')], default='email', max_length=20),
        ),
        migrations.AddField(
            model_name='automation',
            name='conditions',
            field=models.JSONField(blank=True, default=dict, help_text='Additional conditions (e.g., lead_status, source)'),
        ),
        migrations.AddField(
            model_name='automation',
            name='delay_days',
            field=models.IntegerField(default=0, help_text='Delay in days before triggering'),
        ),
        migrations.AddField(
            model_name='automation',
            name='delay_hours',
            field=models.IntegerField(default=24, help_text='Delay in hours before triggering'),
        ),
        migrations.AddField(
            model_name='automation',
            name='message_template',
            field=models.TextField(blank=True, help_text='Optional message template. Leave empty for AI-generated.'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='trigger',
            field=models.CharField(choices=[('new_lead', 'New Lead Added'), ('lead_status_changed', 'Lead Status Changed'), ('no_contact_days', 'No Contact for X Days'), ('booking_created', 'Booking Created'), ('booking_reminder_hours', 'Booking Reminder (X hours before)'), ('session_completed', 'Session Completed'), ('message_received', 'Message Received')], max_length=50),
        ),
        migrations.AlterField(
            model_name='automation',
            name='type',
            field=models.CharField(choices=[('lead_followup', 'Lead Follow-up'), ('booking_reminder', 'Booking Reminder'), ('confirmation', 'Confirmation'), ('post_session', 'Post-Session Follow-up'), ('crm_update', 'CRM Record Update')], max_length=50),
        ),
    ]
