# Generated by Django 4.2.7 on 2025-11-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_automation_channel_automation_conditions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='trigger',
            field=models.CharField(choices=[('new_lead', 'New Lead Added'), ('lead_status_changed', 'Lead Status Changed'), ('no_contact_days', 'No Contact for X Days'), ('booking_created', 'Booking Created'), ('booking_reminder_hours', 'Booking Reminder (X hours before)'), ('booking_cancelled', 'Booking Cancelled'), ('session_completed', 'Session Completed'), ('no_show', 'No Show'), ('message_received', 'Message Received')], max_length=50),
        ),
    ]
