# Generated by Django 4.2.7 on 2025-11-14 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0003_alter_automation_trigger'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='type',
            field=models.CharField(choices=[('lead_followup', 'Lead Follow-up'), ('booking_reminder', 'Booking Reminder'), ('confirmation', 'Confirmation'), ('post_session', 'Post-Session Follow-up'), ('crm_update', 'CRM Record Update'), ('no_show_followup', 'No-Show Follow-up')], max_length=50),
        ),
    ]
